packageNum: 649
packageIdent: knb-lter-cap.649.3
title: 'Micrometeorological conditions at the CAP LTER flux tower located in the west Phoenix, AZ, USA neighborhood of Maryvale (2010-2019)'
geographicCoverage:
  geographicDescription: 'CAP LTER study area: greater Phoenix, Arizona (USA) metropolitan
    area and surrounding Sonoran desert region'
